---

mysql_datadir: /var/log/mysql
mysql_socket: /var/log/mysql/mysql.sock
mysql_port: 3306
mysql_log_bin: /var/log/mysql/mysql_binary_log
mysql_log: /var/log/mysqld.log
mysql_pid_dir: /var/run/mysqld
mysql_pid_file: "{{ mysql_pid_dir }}/mysqld.pid"
mysql_root_password: changeme

databases:
  scm:
    name: 'scm'
    user: 'scm'
    pass: 'scm_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
  amon:
    name: 'amon'
    user: 'amon'
    pass: 'amon_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
  rman:
    name: 'rman'
    user: 'rman'
    pass: 'rman_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
  nav:
    name: 'nav'
    user: 'nav'
    pass: 'nav_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
  navms:
    name: 'navms'
    user: 'navms'
    pass: 'navms_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
  metastore:
    name: 'metastore'
    user: 'hive'
    pass: 'hive_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
  sentry:
    name: 'sentry'
    user: 'sentry'
    pass: 'sentry_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
  hue:
    name: 'hue'
    user: 'hue'
    pass: 'hue_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
  oozie:
    name: 'oozie'
    user: 'oozie'
    pass: 'oozie_password'
    type: 'mysql'
    host: 'localhost'
    port: '3306'
