---

- include_vars: "{{ inventory_dir }}/group_vars/scm_server.yml"

- include: 36322.yml

- name: Install Cloudera Manager Agents
  yum:
    name:
    - cloudera-manager-daemons
    - cloudera-manager-agent
    update_cache: yes
    state: installed

- name: Deploy CM Agent config ini
  template:
    src: config.ini.j2
    dest: /etc/cloudera-scm-agent/config.ini
    group: root
    owner: root
    mode: '0644'

- name: Restart Cloudera Manager Agents
  service: name=cloudera-scm-agent state=restarted enabled=yes
