---
# Cloudera playbook

- name: Apply pre-reqs fix
  hosts: cdh_servers:kts_servers:kms_servers
  roles:
    - pre_reqs
  tags: [pre_reqs, pre_build]

- name: Configure Cloudera Manager Repository
  hosts: cdh_servers:kts_servers:kms_servers
  roles:
    - cm_repo
  tags: [cm_repo, pre_build]

- name: Install rngd
  hosts: cdh_servers:kts_servers:kms_servers
  roles:
    - rngd
  tags: [rngd, pre_build]

- name: Install Java
  hosts: cdh_servers:kts_servers:kms_servers
  roles:
    - java
  tags: [java, pre_build]

- name: Install database server and create databases
  hosts: db_server
  roles:
    - { role: mariadb, when: database_type == 'mysql' }
#    - { role: postgres, when: database_type == 'postgres' }
  tags: mysql

- name: Install DB Connectors
  hosts: cdh_servers
  roles:
    - db_connector
    - mysql_connector
  tags: [db_connector, pre_build]

- name: Install MIT KDC Server
  hosts: krb5_server
  roles:
    - { role: krb5_server, when: krb5_kdc_type == 'mit' }
  tags: [krb5, pre_build]

- name: Configure CA
  hosts: ca_server
  roles:
    - ca_server
  tags: ca_server

- name: Setup certificates
  hosts: all
  roles:
    - certs
  tags: certs

- name: Sign Certs
  hosts: ca_server
  roles:
    - ca_server_signing
  tags: ca_server_signing

- name: Install certificates
  hosts: all
  roles:
    - certs_signed_install
  tags: certs_signed_install

- name: Install Cloudera Manager Agents
  hosts: cdh_servers:kts_servers:kms_servers
  roles:
    - cm_agents
  tags: cm_agents

# Must be done after the cm_agents role otherwise the local users do not exist
- name: Create Data Node directories
  hosts: worker_servers 
  roles:
    - dn_dir_creation 
  tags: dn_dir_creation 

# Must be done after the cm_agents role otherwise the local users do not exist
- name: Create Master Node Directories
  hosts: master_servers
  roles:
    - nn_dir_creation
  tags: nn_dir_creation

- name: Install Cloudera Manager Python API
  hosts: scm_server
  roles:
    - cm_api
  tags: [cm_install]

- name: Install Cloudera Manager Server
  hosts: scm_server
  roles:
    - scm
  tags: [cm_cluster_template, cm_install]

#- name: Map Cloudera Manager Roles to LDAP groups
#  hosts: scm_server
#  roles:
#    - cm_roles
#  tags: [cm_roles, cm_install]

- name: Install Cloudera Manager Agents - tls
  hosts: cdh_servers:kts_servers:kms_servers
  roles:
    - cm_agents_tls
  tags: [cm_agents_tls, cm_install]

- name: Install CDH
  hosts: scm_server
  roles:
    - cdh
  tags: 
  - cdh_cluster_install

- name: Install KTS
  hosts: scm_server
  roles:
    - { role: kts, when: hdfs_tde_enabled == 'True' }
  tags:
  - kts_cluster_template

- name: Sync KTS keys
  hosts: kts_servers
  roles:
    - { role: kts_key_sync, when: hdfs_tde_enabled == 'True' }
  tags:
  - kts_key_sync

- name: Sync KMS keys
  hosts: kms_servers
  roles:
    - { role: kms_key_sync, when: hdfs_tde_enabled == 'True' }
  tags:
  - kms_key_sync

- name: Create Encryption Zones
  hosts: master_servers
  roles:
    - { role: kms_encryption_zones, when: hdfs_tde_enabled == 'True' }
  tags:
  - enc_zones

- name: Install and Configure HAProxy
  hosts: haproxy
  roles:
    - haproxy
  tags: haproxy
