---
# Cloudera playbook

- name: Configure CA
  hosts: ca_server
  roles:
    - ca_server
  tags: ca_server

- name: Setup certificates
  hosts: all
  roles:
    - certs
  tags: certs

- name: Sign Certs
  hosts: ca_server
  roles:
    - ca_server_signing
  tags: ca_server_signing

- name: Install certificates
  hosts: all
  roles:
    - certs_signed_install
  tags: certs_signed_install
