---
# Cloudera playbook teardown

- name: Stop account lockouts
  hosts: scm_server
  roles:
    - lockout_block

- name: Dir teardown
  hosts: all
  roles:
    - dir_teardown
  tags: dir_teardown

- name: CDH DB teardown
  hosts: scm_server
  tasks:
    - include_vars: "{{ inventory_dir }}/group_vars/db_server.yml"
  roles:
    - { role: db_teardown_mysql_cdh, when: database_type == 'mysql' }
    - { role: db_teardown_oracle_cdh, when: database_type == 'oracle' }
  tags: db_teardown_cdh

- name: Remove HAProxy
  hosts: haproxy
  roles:
    - haproxy_teardown
  tags: haproxy_teardown

- name: CM Agent teardown
  hosts: all
  roles:
    - cm_agents_teardown
  tags: cm_agents_teardown

- name: CM Server teardown
  hosts: scm_server
  roles:
    - cm_server_teardown
  tags: cm_server_teardown

- name: CM DB teardown
  hosts: db_server
  roles:
    - { role: db_teardown_mysql_cm, when: database_type == 'mysql' }
    - { role: db_teardown_oracle_cm, when: database_type == 'oracle' }
  tags: db_teardown_cm

- name: CM server yum package removal
  hosts: scm_server
  roles:
    - { role: yum_teardown_cm_server, when: full_teardown == 'True' }
  tags: yum_teardown_cm_server

- name: CM agent yum package removal
  hosts: cdh_servers:kts_servers:kms_servers
  roles:
    - { role: yum_teardown_cm_agent, when: full_teardown == 'True' }
  tags: yum_teardown_cm_agent

