---

- include_vars: "{{ inventory_dir }}/group_vars/db_server.yml"

- name: Create databases
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.value.name }}"
    state: present
    encoding: "{{ item.value.encoding }}" 
    config_file: "/etc/my.cnf"
    login_unix_socket: "{{ mysql_socket }}"
  with_dict: "{{ databases }}"

- name: Create database users
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.value.user }}"
    password: "{{ item.value.pass }}"
    update_password: always
    priv: "{{ item.value.name }}.*:ALL"
    host: "%"
    state: present
    config_file: "/etc/my.cnf"
    login_unix_socket: "{{ mysql_socket }}"
  with_dict: "{{ databases }}"
