- name: Stop HAProxy
  service:
    name: haproxy
    state: stopped
  ignore_errors: true
        
- name: Delete combined key and pem
  file:
    path: /etc/haproxy/combinedKeyAndCert.pem
    state: absent
        
- name: Delete HAProxy config
  file:
    path: /etc/haproxy/haproxy.cfg
    state: absent
        
- name: Install HAProxy
  yum: 
    name: haproxy
    state: absent
  ignore_errors: true
