---
- include_vars: "{{ inventory_dir }}/group_vars/pki.yml"
- include_vars: "{{ inventory_dir }}/group_vars/ca.yml"

#- name: Install {{ openssl_path }}
#  yum:
#    name: {{ openssl_path }}
#    state: latest

- name: Prepare security directories
  file:
    state: directory
    path: "{{ tls.security_root }}"
    mode: 0755
    owner: root

- name: Prepare security subdirs
  file:
    state: directory
    path: "{{ tls.security_root }}/{{ item }}"
    mode: 0755
    owner: root
  with_items:
    - "x509"
    - "jks"
    - "CAcerts"

- name: Create JKS file
  shell: "{{ tls.keytool_path }} -genkeypair -alias {{ inventory_hostname_short }} -keyalg RSA -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -keysize 2048 -dname \"CN={{ inventory_hostname }},{{ ca_ou | map('regex_replace', '^', 'OU=') | join(', ')  }},O={{ ca_org_name }},ST={{ ca_state_or_province }},C={{ ca_countryname_default }}\" -ext san=dns:{{ inventory_hostname }} -storepass {{ tls.keystore_password }} -keypass {{ tls.keystore_password }} -storetype jks"
  args:
    creates: "{{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks"

- name: Change permisions on JKS file
  file:
    state: file
    path: "{{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks"
    mode: 0644
    owner: root

- name: Check JKS contains a private key
  shell: "{{ tls.keytool_path }} -list -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -alias {{ inventory_hostname_short }} -storepass {{ tls.keystore_password }} | grep PrivateKeyEntry"

- name: Push ca files
  copy:
    src: "{{ item }}"
    dest: "{{ tls.security_root }}/CAcerts"
    mode: 0744
  with_items:
    - "{{ signed_certificates_local_location }}/{{ chain_cert_name }}"
    - "{{ signed_certificates_local_location }}/{{ intermediate_ca_cert_name }}"
    - "{{ signed_certificates_local_location }}/{{ root_ca_cert_name }}"

- set_fact:
    root_ca_present: False

- name: Check Root CA is present
  shell: "{{ tls.keytool_path }} -list -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -storepass {{ tls.keystore_password }} -storetype jks -alias {{ tls.root_ca_alias }}"
  register: root_ca_check
  ignore_errors: yes

- set_fact:
    root_ca_present: True
  when: root_ca_check.rc == 0

- name: Check Root CA is correct
  shell: "[[ $({{ openssl_path }} x509 -noout -modulus -in {{ tls.security_root }}/CAcerts/{{ root_ca_cert_name }} | {{ openssl_path }} md5) == $({{ tls.keytool_path }} -list -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -storepass {{ tls.keystore_password }} -storetype jks -alias {{ tls.root_ca_alias }} -rfc | {{ openssl_path }} x509 -inform pem -modulus -noout | {{ openssl_path }} md5) ]]"
  when: root_ca_present == True
  ignore_errors: yes
  register: root_ca_correctness

- name: Remove incorrect Root CA
  shell: "{{ tls.keytool_path }} -delete -alias {{ tls.root_ca_alias }} -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -storepass {{ tls.keystore_password }}"
  when: root_ca_present == True and root_ca_correctness.rc != 0

- set_fact:
    root_ca_present: False
  when: root_ca_present == True and root_ca_correctness.rc != 0

- name: Install Root CA cert into JKS
  shell: "{{ tls.keytool_path }} -importcert -alias {{ tls.root_ca_alias }} -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -file {{ item }} -storepass {{ tls.keystore_password }} -noprompt -trustcacerts"
  with_items:
    - "{{ tls.security_root }}/CAcerts/{{ root_ca_cert_name }}"
  when: root_ca_present == False

- set_fact:
    int_ca_present: False

- name: Check Intermediate CA is present
  shell: "{{ tls.keytool_path }} -list -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -storepass {{ tls.keystore_password }} -storetype jks -alias {{ tls.intermediate_ca_alias }}"
  register: int_ca_check
  ignore_errors: yes

- set_fact:
    int_ca_present: True
  when: int_ca_check.rc == 0

- name: Check Intermediate CA is correct
  shell: "[[ $({{ openssl_path }} x509 -noout -modulus -in {{ tls.security_root }}/CAcerts/{{ intermediate_ca_cert_name }} | {{ openssl_path }} md5) == $({{ tls.keytool_path }} -list -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -storepass {{ tls.keystore_password }} -storetype jks -alias {{ tls.intermediate_ca_alias }} -rfc | {{ openssl_path }} x509 -inform pem -modulus -noout | {{ openssl_path }} md5) ]]"
  when: int_ca_present == True
  ignore_errors: yes
  register: int_ca_correctness

- name: Remove incorrect Intermediateoot CA
  shell: "{{ tls.keytool_path }} -delete -alias {{ tls.intermediate_ca_alias }} -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -storepass {{ tls.keystore_password }}"
  when: int_ca_present == True and int_ca_correctness.rc != 0

- set_fact:
    int_ca_present: False
  when: int_ca_present == True and int_ca_correctness.rc != 0

- name: Install Intermediate CA cert into JKS
  shell: "{{ tls.keytool_path }} -importcert -alias {{ tls.intermediate_ca_alias }} -keystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -file {{ item }} -storepass {{ tls.keystore_password }} -noprompt -trustcacerts"
  with_items:
    - "{{ tls.security_root }}/CAcerts/{{ intermediate_ca_cert_name }}"
  when: int_ca_present == False

- name: Check if the exported key exists
  file:
    path: "{{ tls.security_root }}/x509/{{ inventory_hostname_short }}.key"
    state: file
    mode: 0644
  register: keystatus
  ignore_errors: yes

- name: Export PKCS12
  shell: "{{ tls.keytool_path }} -importkeystore -srckeystore {{ tls.security_root }}/jks/{{ inventory_hostname_short }}.jks -destkeystore {{ tls.security_root }}/x509/{{ inventory_hostname_short }}.p12 -deststoretype PKCS12 -srcstorepass {{ tls.keystore_password }} -srckeypass {{ tls.keystore_password }} -deststorepass {{ tls.keystore_password }} -destkeypass {{ tls.keystore_password }} -srcalias {{ inventory_hostname_short }} -destalias {{ inventory_hostname_short }}"
  when: keystatus is failed

- name: Export Key
  shell: "{{ openssl_path }} pkcs12 -in {{ tls.security_root }}/x509/{{ inventory_hostname_short }}.p12 -nocerts -out {{ tls.security_root }}/x509/{{ inventory_hostname_short }}.key -passout pass:{{ tls.keystore_password }} -passin pass:{{ tls.keystore_password }}"
  when: keystatus is failed

- name: Change permisions on Key
  file:
    state: file
    path: "{{ tls.security_root }}/x509/{{ inventory_hostname_short }}.key"
    mode: 0644
    owner: root

- name: Delete PKCS12
  file:
    state: absent
    path: "{{ tls.security_root }}/x509/{{ inventory_hostname_short }}.p12"

- name: Write key password
  shell: "echo {{ tls.keystore_password }} > {{ tls.security_root }}/x509/key.pw"
  args:
    creates: "{{ tls.security_root }}/x509/key.pw"

- name: Change password permissions
  file:
    state: file
    path: "{{ tls.security_root }}/x509/key.pw"
    mode: 0600
    owner: root
    group: root

- name: Protect key password
  acl:
    path: "{{ tls.security_root }}/x509/key.pw"
    entity: "{{ item }}"
    etype: user
    permissions: r
    state: present
  with_items: "{{ tls.key_password_acl_groups }}"


- name: Write unencrypted key
  shell: "{{ openssl_path }} rsa -in {{ tls.security_root }}/x509/{{ inventory_hostname_short }}.key -passin pass:{{ tls.keystore_password }} -out {{ tls.security_root }}/x509/localhost.key.unenc"
  args:
    creates: "{{ tls.security_root }}/x509/localhost.key.unenc"

- name: Change permisions on unencrypted key
  file:
    state: file
    path: "{{ tls.security_root }}/x509/localhost.key.unenc"
    mode: 0600
    owner: root


- name: Protect unencrypted key
  acl:
    path: "{{ tls.security_root }}/x509/localhost.key.unenc"
    entity: "{{ item }}"
    etype: user
    permissions: r
    state: present
  with_items: "{{ tls.unenc_key_acl_groups }}"

- set_fact:
    subject_alternative_names_local:
      - "{{ inventory_hostname }}"

- set_fact:
    subject_alternative_names: "{{ subject_alternative_names_local + subject_alternative_names }}"
  when: subject_alternative_names is defined

- set_fact:
    subject_alternative_names: "{{ subject_alternative_names_local }}"
  when: subject_alternative_names is not defined

- name: "set SUBJECT var"
  set_fact:
    subject: "/C={{ ca_countryname_default }}/O={{ ca_org_name }}/{{ ca_ou | map('regex_replace', '^', 'OU=') | join('/')  }}/CN={{ inventory_hostname }}"

- name: Install root ca openssl.cnf
  template:
    src: csr.cnf.j2
    dest: "{{ tls.security_root }}/x509/csr.cnf"
    owner: root
    mode: '0644'

- name: Generate CSR
  shell: "{{ openssl_path }} req -key {{ tls.security_root }}/x509/{{ inventory_hostname_short }}.key -passin pass:{{ tls.keystore_password }} -subj \"{{ subject }}\" -config {{ tls.security_root }}/x509/csr.cnf -new -out {{ tls.security_root }}/x509/{{ inventory_hostname_short }}.csr"

- name: Prepare directory for csrs
  local_action:
    module: file
    state: directory
    mode: 0777
    owner: "{{ ansible_user_id }}"
    path: "{{ csr_certificates_local_location }}"

- name: Fetch certificate signing requests
  fetch:
    src: "{{ tls.security_root }}/x509/{{ inventory_hostname_short }}.csr"
    dest: "{{ csr_certificates_local_location }}/"
    flat: yes
  ignore_errors: yes

- name: Check cacerts_file exists
  local_action:
    module: file
    path: "{{ tls.cacerts_file }}"
    state: file

- set_fact:
    jssecacerts_local_location: "{{ signed_certificates_local_location }}/jssecacerts"

- name: Prepare directory for signed certs
  local_action:
    module: file
    state: directory
    mode: 0777
    owner: "{{ ansible_user_id }}"
    path: "{{ signed_certificates_local_location }}"

- name: Copy cacerts to jssecacerts
  local_action: shell cp {{ tls.cacerts_file }} {{ jssecacerts_local_location }}
  run_once: true
  args:
    creates: "{{ jssecacerts_local_location }}"

- name: Check cacerts_file exists
  local_action:
    module: file
    path: "{{ jssecacerts_local_location }}"
    mode: 0744
    state: file
  run_once: true

- name: Change jssecacerts away from default
  local_action: shell {{ tls.keytool_path }} -storepasswd -storepass changeit -keystore {{ jssecacerts_local_location }} -new {{ tls.truststore_password }}
  run_once: true
  ignore_errors: yes

- set_fact:
    root_ca_present: False
  run_once: true

- name: Check Root CA is present in jssecacerts
  local_action: shell {{ tls.keytool_path }} -list -keystore {{ jssecacerts_local_location }} -storepass {{ tls.truststore_password }} -storetype jks -alias {{ tls.root_ca_alias }}
  register: root_ca_check
  run_once: true
  ignore_errors: yes

- set_fact:
    root_ca_present: True
  when: root_ca_check.rc == 0
  run_once: true

- name: Check Root CA is correct in jssecacerts
  local_action: shell [[ $({{ openssl_path }} x509 -noout -modulus -in {{ tls.security_root }}/CAcerts/{{ root_ca_cert_name }} | {{ openssl_path }} md5) == $({{ tls.keytool_path }} -list -keystore {{ jssecacerts_local_location }} -storepass {{ tls.truststore_password }} -storetype jks -alias {{ tls.root_ca_alias }} -rfc | {{ openssl_path }} x509 -inform pem -modulus -noout | {{ openssl_path }} md5) ]]
  when: root_ca_present == True
  ignore_errors: yes
  register: root_ca_correctness
  run_once: true

- name: Remove incorrect Root CA from jssecacerts
  local_action: shell {{ tls.keytool_path }} -delete -alias {{ tls.root_ca_alias }} -keystore {{ jssecacerts_local_location }} -storepass {{ tls.truststore_password }}
  when: root_ca_present == True and root_ca_correctness.rc != 0
  run_once: true

- set_fact:
    root_ca_present: False
  when: root_ca_present == True and root_ca_correctness.rc != 0
  run_once: true

- name: Install Root CA cert into jssecacerts
  local_action: shell {{ tls.keytool_path }} -importcert -alias {{ tls.root_ca_alias }} -keystore {{ jssecacerts_local_location }} -file {{ item }} -storepass {{ tls.truststore_password }} -noprompt -trustcacerts
  with_items:
    - "{{ tls.security_root }}/CAcerts/{{ root_ca_cert_name }}"
  when: root_ca_present == False
  run_once: true

- set_fact:
    int_ca_present: False
  run_once: true

- name: Check Intermediate CA is present in jssecacerts
  local_action: shell {{ tls.keytool_path }} -list -keystore {{ jssecacerts_local_location }} -storepass {{ tls.truststore_password }} -storetype jks -alias {{ tls.intermediate_ca_alias }}
  register: int_ca_check
  ignore_errors: yes
  run_once: true

- set_fact:
    int_ca_present: True
  when: int_ca_check.rc == 0
  run_once: true

- name: Check Intermediate CA is correct in jssecacerts
  local_action: shell [[ $({{ openssl_path }} x509 -noout -modulus -in {{ tls.security_root }}/CAcerts/{{ intermediate_ca_cert_name }} | {{ openssl_path }} md5) == $({{ tls.keytool_path }} -list -keystore {{ jssecacerts_local_location }} -storepass {{ tls.truststore_password }} -storetype jks -alias {{ tls.intermediate_ca_alias }} -rfc | {{ openssl_path }} x509 -inform pem -modulus -noout | {{ openssl_path }} md5) ]]
  when: int_ca_present == True
  ignore_errors: yes
  register: int_ca_correctness
  run_once: true

- name: Remove incorrect Intermediateoot CA from jssecacerts
  local_action: shell {{ tls.keytool_path }} -delete -alias {{ tls.intermediate_ca_alias }} -keystore {{ jssecacerts_local_location }} -storepass {{ tls.truststore_password }}
  when: int_ca_present == True and int_ca_correctness.rc != 0
  run_once: true

- set_fact:
    int_ca_present: False
  when: int_ca_present == True and int_ca_correctness.rc != 0
  run_once: true

- name: Install Intermediate CA cert into jssecacerts
  local_action: shell {{ tls.keytool_path }} -importcert -alias {{ tls.intermediate_ca_alias }} -keystore {{ jssecacerts_local_location }} -file {{ item }} -storepass {{ tls.truststore_password }} -noprompt -trustcacerts
  with_items:
    - "{{ tls.security_root }}/CAcerts/{{ intermediate_ca_cert_name }}"
  when: int_ca_present == False
  run_once: true

- name: Distribute jssecacerts file
  copy:
    src: "{{ jssecacerts_local_location }}"
    dest: "{{ tls.truststore_path }}"
    mode: 0644

- name: Update CA Certs for Ansible
  blockinfile:
    path: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    block: "{{ lookup('file', '{{ tls.cert_chain }}') }}"
