---

- name: Add Cloudera Manager yum repository
  yum_repository:
    name: cloudera-manager
    description: Cloudera Manager
    baseurl: "{{ scm_repo_url }}"
    gpgkey: "{{ scm_repo_gpgkey }}"
    gpgcheck: no
    enabled: yes
  when:
  - ansible_os_family|lower == "redhat"
