---

- include_vars: "{{ inventory_dir }}/group_vars/pki.yml"
- include_vars: "{{ inventory_dir }}/group_vars/scm_server.yml"
- include_vars: "{{ inventory_dir }}/group_vars/scm_server_enc.yml"

- name: Install Cloudera Manager Agents
  yum:
    name:
      - cloudera-manager-daemons
      - cloudera-manager-agent
    state: installed

- name: Deploy CM Agent config ini
  template:
    src: config.ini.j2
    dest: /etc/cloudera-scm-agent/config.ini
    group: root
    owner: root
    mode: '0644'

#- name: Configure Cloudera Manager Agent 'server_host'
#  lineinfile: dest=/etc/cloudera-scm-agent/config.ini regexp=^server_host line=server_host={{ hostvars[scm_hostname]['inventory_hostname'] }}

#- name: Configure Clouder Manager Agent use_tls
#  lineinfile: dest=/etc/cloudera-scm-agent/config.ini regexp=^use_tls line=use_tls={{ use_tls  }}

- name: Restart Cloudera Manager Agents
  service: name=cloudera-scm-agent state=restarted enabled=yes
